'use strict';
const path=require('path'),fs=require('fs'),assert=require('assert/strict'),http=require('http');
const work=path.resolve(__dirname,'../..'),root=path.resolve(process.env.SOCIAL_EVIDENCE_DIR || path.join(work,'artifacts/social-core-runtime')),back=path.join(work,'backend-v2');
fs.mkdirSync(path.join(root,'tmp'),{recursive:true});fs.mkdirSync(path.join(root,'evidence'),{recursive:true});
Object.assign(process.env,{NODE_ENV:'test',DB_PATH:path.join(root,'tmp','browser.sqlite'),UPLOADS_ROOT:path.join(root,'tmp','browser-uploads'),DISABLE_CSRF:'1',DISABLE_RATE_LIMIT:'1',INVITE_CODE:'123456',JWT_SECRET:'synthetic_browser_social_jwt_32_characters',ADMIN_JWT_SECRET:'synthetic_browser_admin_jwt_32_characters'});
const express=require(path.join(back,'node_modules/express')),app=require(path.join(back,'src/app'));
const webSnapshot=path.join(root,'tmp','browser-web');fs.cpSync(path.join(work,'web/dist'),webSnapshot,{recursive:true});
const outer=express();outer.get('/config.json',(_req,res)=>res.json({api:'http://127.0.0.1:'+server.address().port,socket:'http://127.0.0.1:'+server.address().port,version:'isolated-test'}));outer.use(express.static(webSnapshot));
outer.use((req,res,next)=>!req.path.startsWith('/api')&&!req.path.startsWith('/uploads')&&req.method==='GET'?res.sendFile(path.join(webSnapshot,'index.html')):next());outer.use(app);
const server=http.createServer(outer),io=new(require(path.join(back,'node_modules/socket.io')).Server)(server);app.set('io',io);require(path.join(back,'src/realtime'))(io,app);
const {chromium}=require(path.join(work,'desktop-electron/node_modules/playwright'));
let browser,page;const result={checks:[],errors:[],externalRequestsBlocked:0};
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;require(path.join(back,'src/config')).allowedOrigins.push(base);
 async function api(method,url,body,token){const r=await fetch(base+url,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!r.ok)throw new Error(method+' '+url+' -> '+r.status+' '+(await r.json()).error);return r.json();}
 const suffix=String(Date.now()).slice(-7);const phoneA='1391'+suffix,phoneB='1392'+suffix,password='SyntheticSocial123!';
 const a=await api('POST','/api/auth/register',{phone:phoneA,password,username:'审计A'+suffix,inviteCode:process.env.INVITE_CODE});
 const b=await api('POST','/api/auth/register',{phone:phoneB,password,username:'审计B'+suffix,inviteCode:process.env.INVITE_CODE});
 await api('POST','/api/users/friend-request',{toId:b.user.id},a.token);
 const requests=await api('GET','/api/users/friend-requests',null,b.token);
 await api('POST','/api/users/friend-request/'+requests[0].id+'/handle',{action:'accept'},b.token);
 const group=await api('POST','/api/messages/conversation/group',{name:'隔离测试群',memberIds:[b.user.id]},a.token);
 const dm=await api('POST','/api/messages/conversation/private',{userId:b.user.id},a.token);
 let context;
 if (process.env.SOCIAL_ELECTRON === '1') {
   const profile=path.join(root,'tmp','electron-profile');fs.mkdirSync(profile,{recursive:true});
   fs.writeFileSync(path.join(profile,'config.json'),JSON.stringify({serverUrl:base}));
   const bootstrap=path.join(work,'desktop-electron','social-test-bootstrap.cjs');
   fs.writeFileSync(bootstrap, `const {app,session}=require('electron');
     app.setPath('userData', ${JSON.stringify(profile)});
     const http=require('http');
     require('https').get=(url,options,callback)=>http.get(${JSON.stringify(base)}+'/config.json',callback);
     app.whenReady().then(()=>session.defaultSession.webRequest.onBeforeRequest((details,cb)=>cb({cancel: /^https?:/.test(details.url)&&!details.url.startsWith(${JSON.stringify(base)})})));
     require('./src/main.js');`);
   const { _electron }=require(path.join(work,'desktop-electron/node_modules/playwright'));
   const electronEnv={...process.env};delete electronEnv.ELECTRON_RUN_AS_NODE;
   browser=await _electron.launch({timeout:30000,args:[bootstrap,...(process.platform==='linux'?['--no-sandbox']:[])],env:electronEnv});
   context=browser.context();page=await browser.firstWindow();
   result.runtime=await browser.evaluate(({app})=>({platform:process.platform,packaged:app.isPackaged,electron:process.versions.electron}));
 } else {
   browser=await chromium.launch({headless:true,...(process.env.SOCIAL_CHROMIUM?{executablePath:process.env.SOCIAL_CHROMIUM}:{}),args:['--no-sandbox']});
   context=await browser.newContext({viewport:{width:1440,height:980},serviceWorkers:'block'});
 }
 await context.route('**/*',async route=>{const u=route.request().url();if(u.includes('/config.json'))return route.fulfill({json:{api:base,socket:base,cdn:base,version:'isolated-test'}});if(!u.startsWith(base)&&!u.startsWith('file:')&&!u.startsWith('data:')&&!u.startsWith('blob:')){result.externalRequestsBlocked++;return route.abort();}return route.continue();});
 if(!page) page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>result.errors.push(e.message));
 result.stage='login A';if(process.env.SOCIAL_ELECTRON==='1') await page.reload(); else await page.goto(base+'/login');await page.getByTestId('login-phone-input').fill(phoneA);await page.getByTestId('login-password-input').fill(password);await page.getByTestId('login-submit-btn').click();
 await page.getByTestId('conv-item-'+group.conversationId).click();await page.getByTestId('chat-msg-input').fill('仅属于测试A的草稿');
 result.stage='add B';await page.getByTestId('account-switcher').click();await page.getByTestId('account-add-row').click();await page.getByTestId('account-add-phone').fill(phoneB);await page.getByTestId('account-add-password').fill(password);await page.getByTestId('account-add-submit').click();
 result.stage='B draft check';await page.getByTestId('conv-item-'+group.conversationId).click();await page.waitForFunction(()=>document.querySelector('[data-testid="chat-msg-input"]')?.value==='');
 assert.equal(await page.getByTestId('chat-msg-input').inputValue(),'');result.checks.push('A draft -> add/switch B -> empty composer');await page.screenshot({path:path.join(root,'evidence','browser-b-isolated.png')});
 await page.getByTestId('chat-msg-input').fill('仅属于测试B的草稿');await page.getByTestId('account-switcher').click();result.stage='back A';await Promise.all([page.waitForEvent('load'),page.getByTestId('account-row-'+a.user.id).click()]);
 await page.getByTestId('conv-item-'+group.conversationId).click();await page.waitForFunction(()=>document.querySelector('[data-testid="chat-msg-input"]')?.value==='仅属于测试A的草稿');result.checks.push('Switch back A restores its draft');
 result.stage='reload A';await page.reload();await page.getByTestId('conv-item-'+group.conversationId).click();await page.waitForFunction(()=>document.querySelector('[data-testid="chat-msg-input"]')?.value==='仅属于测试A的草稿');result.checks.push('A draft survives browser reload');
 await page.waitForFunction(()=>window.__touliaoSocket?.connected);
 await api('PUT','/api/users/contacts/'+b.user.id+'/remark',{remark:'跨端备注验证'},a.token);
 await page.getByTestId('conv-item-'+dm.conversationId).filter({hasText:'跨端备注验证'}).waitFor();result.checks.push('HTTP remark on another session updates open conversation list through Socket.IO');
 await context.setOffline(true);await api('PUT','/api/users/contacts/'+b.user.id+'/remark',{remark:'离线恢复备注'},a.token);await context.setOffline(false);
 await page.getByTestId('conv-item-'+dm.conversationId).filter({hasText:'离线恢复备注'}).waitFor({timeout:30000});result.checks.push('Reconnect reconciles offline remark change');
 result.stage='preference sync';
 await page.getByTestId('conv-item-'+dm.conversationId).click();await page.getByTestId('chat-group-info-btn').click();
 const mute=page.locator('.wc-settings-panel').getByRole('switch').first();await mute.waitFor();
 await api('POST','/api/messages/conversation/'+dm.conversationId+'/mute',{muted:1},a.token);
 await page.waitForFunction(()=>document.querySelector('.wc-settings-panel [role="switch"]')?.getAttribute('aria-checked')==='true');
 result.checks.push('Another session changes mute; open settings updates through invalidation and authoritative GET');
 await mute.click();await page.waitForFunction(()=>document.querySelector('.wc-settings-panel [role="switch"]')?.getAttribute('aria-checked')==='false');
 assert.equal((await api('GET','/api/messages/conversations',null,a.token)).find(c=>c.id===dm.conversationId).muted,0);
 result.checks.push('New Web mute control persists allowed change and renders server truth');
 await page.locator('.wc-settings-close-btn').click();
 result.stage='privacy projection';
 await api('PUT','/api/users/profile',{bio:'测试B受限签名'},b.token);
 await api('PUT','/api/users/me/settings',{profileVisible:false},b.token);
 await page.getByTestId('conv-item-'+dm.conversationId).click();await page.getByTestId('chat-title').click();
 await page.getByText('测试B受限签名',{exact:true}).waitFor();
 assert.equal((await api('GET','/api/users/'+b.user.id,null,a.token)).bio,'测试B受限签名');
 await api('POST','/api/users/block/'+a.user.id,{},b.token);
 await page.getByText('测试B受限签名',{exact:true}).waitFor({state:'hidden'});
 assert.equal((await api('GET','/api/users/'+b.user.id,null,a.token)).bio,'');
 const groupInfo=await api('GET','/api/messages/conversation/'+group.conversationId+'/info',null,a.token);
 assert.equal(groupInfo.members.find(x=>x.id===b.user.id).bio,'');
 result.checks.push('Authorized friend profile visible; blacklist invalidates open profile and redacts HTTP profile/group member response');
 await page.screenshot({path:path.join(root,'evidence','browser-profile-redacted.png')});
 assert.deepEqual(result.errors,[]);result.ok=true;
})().catch(async e=>{result.ok=false;result.failure=e.message;if(page){result.pageText=(await page.locator('body').innerText()).slice(0,2000);result.drafts=await page.evaluate(()=>({input:document.querySelector('[data-testid="chat-msg-input"]')?.value,owned:Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith('touliao_draft_')||k==='touliao_active_owner_v2').map(k=>[k,localStorage.getItem(k)]))}));await page.screenshot({path:path.join(root,'evidence/browser-failure.png')});}process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(root,'evidence/browser-core.json'),JSON.stringify(result,null,2));if(browser)await browser.close();try{fs.unlinkSync(path.join(work,'desktop-electron/social-test-bootstrap.cjs'));}catch{}io.close();server.close();setTimeout(()=>process.exit(process.exitCode||0),100);});
