#!/usr/bin/env python3
"""Assemble a portable native comparison gallery from collected simulator evidence."""
import argparse,json,shutil,subprocess
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--evidence',type=Path,required=True);p.add_argument('--reference',type=Path,required=True)
for flag in ['android-before','android-after','ios-before','ios-after']:p.add_argument('--'+flag,type=Path)
a=p.parse_args();out=a.evidence/'review';out.mkdir(parents=True,exist_ok=True)
images={}
for platform in ['android','ios']:
 for stage in ['before','after']:
  src=getattr(a,platform+'_'+stage);dest=out/'screenshots'/platform/stage;dest.mkdir(parents=True,exist_ok=True)
  if not src or not src.exists():continue
  for image in sorted(src.rglob('*.png')):
   if 'NativeUiReview' not in str(image.parent):continue
   shutil.copy2(image,dest/image.name)
   images[f'{platform}/{stage}/{image.stem}']=str((dest/image.name).relative_to(out))
ref=out/'reference';ref.mkdir(exist_ok=True)
for image in a.reference.glob('mobile-*.png'):shutil.copy2(image,ref/image.name)
labels={'chat-attachments':'聊天附件面板','chat-menu':'聊天操作菜单','login-keyboard-submit':'登录 · 键盘上方的提交按钮','my-qr':'我的二维码','group-qr':'群二维码','quiet-hours':'勿扰时段','change-phone':'更换手机号','change-password':'修改密码','delete-account':'注销账号','accounts':'账号管理','login':'登录','register':'注册','forgot-password':'找回密码说明','conversations':'会话列表','chat':'聊天','files':'会话文件','mentions':'提及我的消息','contacts':'通讯录','add-friend':'添加好友','friend-requests':'好友申请','create-group':'创建群聊','blocked':'黑名单','friend-labels':'好友标签','group':'群资料','invite-members':'邀请群成员','search':'搜索','profile':'个人资料','edit-profile':'编辑资料','settings':'设置','appearance':'外观','notifications':'通知设置','privacy':'隐私与安全','quiet-hours':'勿扰时段','change-phone':'修改手机号','change-password':'修改密码','delete-account':'注销账号','sessions':'登录设备','accounts':'账号管理','call-history':'通话记录','call-controls':'通话控制组件（无真实通话）','wallet':'钱包','favorites':'收藏','moments':'朋友圈','compose-moment':'发布动态','invite-friend':'邀请好友','login-keyboard':'登录 · 模拟器键盘'}
reference={'chat-attachments':'chat','group':'group-detail','files':'files','friend-labels':'contact-tags','profile':'profile','notifications':'notifications','privacy':'privacy','sessions':'devices','accounts':'account','call-controls':'video-call','compose-moment':'publish','moments':'discover','friend-requests':'requests','invite-members':'group-members','chat-menu':'chat'}
references = {f'{page}/{theme}': f'reference/mobile-{theme}-{reference.get(page,page)}.png' for page in labels for theme in ['light','dark'] if (ref/f'mobile-{theme}-{reference.get(page,page)}.png').exists()}
manifest={'images':images,'references':references,'labels':labels,'reference':reference,'nativeBase':'20aef960','reviewCommit':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip()}
(out/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
html=r'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>投聊 · 原生 UI 改版审阅</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f4f6fa;color:#17212e;font:16px/1.6 system-ui,"PingFang SC","Microsoft YaHei",sans-serif}header,main{max-width:1360px;margin:auto;padding:24px}h1{font-size:26px;margin:0}p{margin:10px 0}.muted{color:#616e80;font-size:14px}a{color:#2864f0}select,button{font:inherit;border:1px solid #a9b5c6;border-radius:8px;background:white;padding:8px 12px;margin:4px}nav{position:sticky;top:0;z-index:2;background:#f4f6faf5;border-bottom:1px solid #e7ebf2;padding:10px 20px}.controls{max-width:1320px;margin:auto;display:flex;flex-wrap:wrap;align-items:center;gap:12px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.panel{background:white;border:1px solid #e7ebf2;border-radius:12px;overflow:hidden;padding:16px}.panel h2{font-size:18px;margin:0 0 4px}.panel img{width:100%;height:auto;display:block;border:1px solid #e7ebf2}.missing{padding:60px 16px;color:#687587;background:#f8f9fc}.badge{display:inline-block;border-radius:8px;background:#edf3ff;color:#2864f0;padding:4px 10px;font-size:13px}.reference img{border:0}footer{padding:24px;text-align:center;font-size:14px;color:#687587}@media(max-width:850px){.grid{grid-template-columns:1fr}.panel img{max-width:430px;margin:auto}}@media(prefers-color-scheme:dark){body,nav{background:#10151e;color:#eaf0f8}.panel,select,button{background:#18212d;color:#eaf0f8;border-color:#657892}.muted,footer{color:#a7b4c6}.missing{background:#202b3a;color:#a7b4c6}a{color:#7ca7ff}}</style>
<header><h1>投聊 · Android / iOS 原生改版</h1><p>接续 <code>20aef960</code>，保留此前 Web / Windows 五次提交。代码、设计参考与原生模拟器截图对照。</p><p><span class="badge">仅审阅，未发布 / 未部署</span> <span class="badge">真实原生控件 · 隔离测试接口</span></p><p class="muted">这些图片来自 Android Emulator 或 iOS Simulator 的原生页面，不能代替手机真机、Windows 真机或四端真实音视频联测。无图片的场景明确保留为空；通话控制图为组件布局检查。</p><p><a href="NATIVE-REPORT.md">完成情况、构建和回归记录</a> · <a href="manifest.json">截图索引</a> · <a href="commits.txt">提交清单与接续基点</a> · <a href="previous-web-windows/touliao-ui-review-20260918.zip">此前 Web / Windows 审阅包</a></p></header>
<nav><div class="controls"><label>平台 <select id="platform"><option value="android">Android</option><option value="ios">iOS</option></select></label><label>页面 <select id="page"></select></label><label>主题 <select id="theme"><option value="light">浅色</option><option value="dark">深色</option></select></label><label>字号 / 布局 <select id="size"><option value="normal">标准手机</option><option value="large">320 宽 · 大字号</option></select></label><button id="prev">上一页</button><button id="next">下一页</button></div></nav>
<main><p id="caption"></p><div class="grid"><section class="panel"><h2>改造前</h2><p class="muted">20aef960 的原生 UI，仅加入测试工具</p><div id="before"></div></section><section class="panel"><h2>改造后</h2><p class="muted">新主题、字体、图标和布局</p><div id="after"></div></section><section class="panel reference"><h2>设计参考</h2><p class="muted">用户提供设计包的原型截图，点击查看原图</p><div id="reference"></div></section></div><p class="muted">标准宽度随模拟器不同；320 宽场景是原生布局约束测试。Android 大字号为 Compose fontScale 2，iOS 使用 accessibility3。现有原生导航保留三栏；原型未接入的业务不制造演示按钮。</p></main><footer>查看报告了解验证范围、已知限制及仅回退本轮原生改动的方法。</footer>
<script>const bundle=__MANIFEST__;
const $=id=>document.getElementById(id);for(const [key,label] of Object.entries(bundle.labels)){const o=document.createElement('option');o.value=key;o.textContent=label;$('page').append(o)}
function show(id,path){const el=$(id);el.replaceChildren();if(!path){const msg=document.createElement('div');msg.className='missing';msg.textContent='此组合没有截图，尚未作为通过项验证。';el.append(msg);return}const link=document.createElement('a');link.href=path;link.target='_blank';const image=document.createElement('img');image.src=path;image.alt=$('page').selectedOptions[0].textContent;image.onerror=()=>show(id,null);link.append(image);el.append(link)}
function render(){const page=$('page').value,platform=$('platform').value,large=$('size').value==='large',theme=$('theme').value;const keyboard=page.startsWith('login-keyboard');const stem=keyboard?(theme==='light'&&!large?page:'unavailable-keyboard-variant'):page+'-'+theme+(large?'-large-text':'');for(const stage of ['before','after'])show(stage,bundle.images[platform+'/'+stage+'/'+stem]);show('reference',bundle.references[page+'/'+theme]);$('caption').textContent=bundle.labels[page]+' · '+platform.toUpperCase()+' · '+(theme==='dark'?'深色':'浅色')+(large?' · 大字号 / 窄屏':'')}
for(const id of ['platform','page','theme','size'])$(id).onchange=render;for(const [id,step] of [['prev',-1],['next',1]])$(id).onclick=()=>{const el=$('page');el.selectedIndex=(el.selectedIndex+step+el.length)%el.length;render()};render();</script></html>'''
(out/'index.html').write_text(html.replace('__MANIFEST__',json.dumps(manifest,ensure_ascii=False).replace('<','\\u003c')))
print(json.dumps({'gallery':str(out/'index.html'),'nativeImages':len(images),'designReferences':len(list(ref.glob('*.png')))},ensure_ascii=False))
