// Generated by scripts/generate-native-design.py; do not edit.
import SwiftUI
import UIKit

enum TouliaoDesign {
    private static func adaptive(_ light: UInt32, _ dark: UInt32) -> Color {
        Color(UIColor { traits in
            let value = traits.userInterfaceStyle == .dark ? dark : light
            return UIColor(red: CGFloat((value >> 16) & 255) / 255,
                           green: CGFloat((value >> 8) & 255) / 255,
                           blue: CGFloat(value & 255) / 255,
                           alpha: CGFloat((value >> 24) & 255) / 255)
        })
    }
    static let primary = adaptive(0xFF2864F0, 0xFF7CA7FF)
    static let primaryHover = adaptive(0xFF1D52D5, 0xFF9ABCFF)
    static let primaryActive = adaptive(0xFF1745B4, 0xFF6595F5)
    static let primaryForeground = adaptive(0xFFFFFFFF, 0xFF10151E)
    static let primarySoft = adaptive(0xFFEDF3FF, 0xFF223550)
    static let background = adaptive(0xFFF4F6FA, 0xFF10151E)
    static let surface = adaptive(0xFFFFFFFF, 0xFF18212D)
    static let surfaceSecondary = adaptive(0xFFF8F9FC, 0xFF202B3A)
    static let surfaceHover = adaptive(0xFFF0F3F8, 0xFF273547)
    static let text = adaptive(0xFF17212E, 0xFFEAF0F8)
    static let textMuted = adaptive(0xFF687587, 0xFFA7B4C6)
    static let textDisabled = adaptive(0xFF9AA5B4, 0xFF6C7B90)
    static let border = adaptive(0xFFE7EBF2, 0xFF2D3A4C)
    static let borderStrong = adaptive(0xFFA9B5C6, 0xFF657892)
    static let danger = adaptive(0xFFDC4454, 0xFFFF8492)
    static let dangerSoft = adaptive(0xFFFFF0F2, 0xFF422933)
    static let success = adaptive(0xFF18856B, 0xFF67CCB3)
    static let successSoft = adaptive(0xFFE8F6F1, 0xFF173B35)
    static let warning = adaptive(0xFFA7680C, 0xFFF2BF66)
    static let warningSoft = adaptive(0xFFFFF6E5, 0xFF403624)
    static let overlay = adaptive(0x6B10151E, 0x99000000)
    static let focus = adaptive(0xFF2864F0, 0xFF9ABCFF)
    static let messageIncoming = adaptive(0xFFFFFFFF, 0xFF202B3A)
    static let messageOutgoing = adaptive(0xFF2864F0, 0xFF2E58A2)
    static let messageOutgoingText = adaptive(0xFFFFFFFF, 0xFFFFFFFF)
    static let readableMuted = adaptive(0xFF626E80, 0xFFA7B4C6)
    static let readableDanger = adaptive(0xFFBE3F4E, 0xFFFF8492)
}
