// Generated by scripts/generate-native-design.py; do not edit.
import SwiftUI
import UIKit

enum TouliaoDesign {
    private static func adaptive(_ light: UInt32, _ dark: UInt32) -> Color {
        Color(UIColor { traits in
            let value = traits.userInterfaceStyle == .dark ? dark : light
            return UIColor(red: CGFloat((value >> 16) & 255) / 255,
                           green: CGFloat((value >> 8) & 255) / 255,
                           blue: CGFloat(value & 255) / 255,
                           alpha: CGFloat((value >> 24) & 255) / 255)
        })
    }
    static let primary = adaptive(0xFF5B4CF0, 0xFF6A5BF7)
    static let primaryHover = adaptive(0xFF4E3FE3, 0xFF7A6CFA)
    static let primaryActive = adaptive(0xFF4233CC, 0xFF5B4CF0)
    static let primaryForeground = adaptive(0xFFFFFFFF, 0xFFFFFFFF)
    static let primarySoft = adaptive(0xFFEEEBFF, 0xFF231F48)
    static let background = adaptive(0xFFF2F2F7, 0xFF000000)
    static let surface = adaptive(0xFFFFFFFF, 0xFF1C1C1E)
    static let surfaceSecondary = adaptive(0xFFF7F7FA, 0xFF2C2C2E)
    static let surfaceHover = adaptive(0xFFECECF2, 0xFF3A3A3C)
    static let text = adaptive(0xFF0B0B12, 0xFFF5F5F7)
    static let textMuted = adaptive(0xFF636373, 0xFFA1A1AB)
    static let textDisabled = adaptive(0xFFA1A1AE, 0xFF6E6E78)
    static let border = adaptive(0xFFE3E3EA, 0xFF2C2C2E)
    static let borderStrong = adaptive(0xFFBDBDC9, 0xFF48484A)
    static let danger = adaptive(0xFFD7263D, 0xFFFF6B7D)
    static let dangerSoft = adaptive(0xFFFFEEF0, 0xFF3A1D23)
    static let success = adaptive(0xFF11795F, 0xFF4FD1A5)
    static let successSoft = adaptive(0xFFE6F6F0, 0xFF12332A)
    static let warning = adaptive(0xFF9A5B00, 0xFFFFC45C)
    static let warningSoft = adaptive(0xFFFFF4E0, 0xFF3A2E17)
    static let overlay = adaptive(0x660A0A14, 0x9E000000)
    static let focus = adaptive(0xFF5B4CF0, 0xFF9B90FF)
    static let auroraTeal = adaptive(0xFF5EEAD4, 0xFF5EEAD4)
    static let messageIncoming = adaptive(0xFFE9E9F0, 0xFF2C2C2E)
    static let messageOutgoing = adaptive(0xFF5B4CF0, 0xFF6A5BF7)
    static let messageOutgoingText = adaptive(0xFFFFFFFF, 0xFFFFFFFF)
    static let iconOnDark = adaptive(0xFFFFFFFF, 0xFFFFFFFF)
    static let iconOnLight = adaptive(0xFF0B0B12, 0xFF17212E)
    static let primaryText = adaptive(0xFF5B4CF0, 0xFFA99FFF)
    static let readableMuted = adaptive(0xFF5C5C6B, 0xFFA1A1AB)
    static let readableDanger = adaptive(0xFFB82237, 0xFFFF6B7D)
}
