#!/usr/bin/env python3
"""Check application icon ownership, source geometry and generated platform registries."""
import argparse, hashlib, json, re, subprocess, xml.etree.ElementTree as ET
from pathlib import Path
R=Path(__file__).resolve().parents[1]
p=argparse.ArgumentParser();p.add_argument('--output');args=p.parse_args()
reg=json.loads((R/'web/src/ui-kit/icon-registry.json').read_text())
errors=[]; uses=[]; assets={}; hashes={}; inline=[]
def fail(file,rule,detail):errors.append({'file':str(file.relative_to(R)),'rule':rule,'detail':detail})
for f in sorted((R/'web/src/ui-kit/icons').glob('*.svg')):
 root=ET.fromstring(f.read_text());assets[f.stem]=root
 for key,expected in [('viewBox','0 0 24 24'),('stroke-width',str(reg['strokeWidth'])),('stroke-linecap',reg['linecap']),('stroke-linejoin',reg['linejoin'])]:
  if root.get(key)!=expected:fail(f,'geometry',key)
 # Shape-equivalent duplicate sources are disallowed; registry aliases are allowed.
 shape=ET.tostring(root);h=hashlib.sha256(shape).hexdigest();hashes.setdefault(h,[]).append(f.stem)
for k,a in reg['icons'].items():
 if a not in assets:errors.append({'rule':'missing asset','name':k,'asset':a})
for names in hashes.values():
 if len(names)>1:errors.append({'rule':'duplicate canonical geometry','names':names})
assert len({reg['icons'][x] for x in ['speaker','bluetooth','earpiece']})==3
assert reg['icons']['file']=='paperclip' and reg['icons']['fileContent']=='file-text'
exceptions={'web/src/components/ElectronTitlebar.jsx':'Windows OS window controls',
 'web/src/pages/Login.jsx':'Apple / Android platform download brands',
 'web/src/pages/Register.jsx':'Touliao brand mark',
 'web/src/pages/Home.jsx':'Empty workspace illustration',
 'web/src/components/ContactList.jsx':'Empty contacts illustration'}
props={k[0].upper()+k[1:]:k for k in reg['icons']}
roots=[R/'web/src',R/'ios/Touliao',R/'android/app/src/main/java/com/touliao/app']
for source in roots:
 for f in source.rglob('*'):
  if f.suffix not in ['.jsx','.js','.swift','.kt']:continue
  rel=str(f.relative_to(R));s=f.read_text()
  if f.name in ['DesignIcons.kt','TouliaoIcons.kt','TouliaoIconRegistry.swift'] or '.test.' in f.name:continue
  if f.suffix in ['.jsx','.js']:
   # Mixed JSX text (for example an emoji before a translated label) is also a functional icon.
   jsx=re.sub(r'/\*.*?\*/','',s,flags=re.S)
   for m in re.finditer(r'>\s*([\u2190-\u21ff\u2600-\u27ff\U0001f300-\U0001faff\ufe0f]+)\s*(?=[<{])',jsx):
    fail(f,'functional text icon',m.group(1))
   if re.search(r'\.fillText\(\s*[\"\'][^\"\']*[\u2600-\u27ff\U0001f300-\U0001faff]',s):
    fail(f,'canvas text icon','Use shared registry geometry')
   refs=re.findall(r'<(?:TouliaoIcon|Icon)\s[^>]*?name=["\']([^"\']+)["\']',s)
   for m in re.finditer(r'<svg\b',s):
    if f.name=='Icon.jsx':continue
    if rel not in exceptions:fail(f,'unregistered inline svg',s.count('\n',0,m.start())+1)
    else:inline.append({'file':rel,'line':s.count('\n',0,m.start())+1,'reason':exceptions[rel]})
   if re.search(r'<(?:TouliaoIcon|Icon|Ico\w+)\b[^>]*\bsize=\{\d',s):fail(f,'arbitrary glyph size','Use size token')
  elif f.suffix=='.swift':
   refs=re.findall(r'(?:TouliaoIcon\(|touliaoIcon: )"([^"\n]+)"',s)
   if re.search(r'Image\(systemName:|Label\([^\n]+systemImage:',s):fail(f,'SF Symbols','Business views must use registry')
   if re.search(r'TouliaoIcon\([^\n]*\)(?:\s*\.\w+\([^\n)]*\))*\s*\.foregroundColor\(\.(?:white|black)',s):fail(f,'hardcoded glyph color','Use IconColor or a shared theme token')
  else:
   refs=[props.get(x,'UNKNOWN:'+x) for x in re.findall(r'TouliaoIcons\.(\w+)',s)]
   if 'androidx.compose.material.icons' in s or re.search(r'\bDesignIcons\.',s):fail(f,'native/private icon source','Business views must use semantic registry')
  for name in refs:
   uses.append({'file':rel,'semantic':name,'asset':reg['icons'].get(name)})
   if name not in reg['icons']:fail(f,'unregistered semantic',name)
# Verify actual generated bytes, not only that a generator exists.
check=subprocess.run(['python3',str(R/'scripts/generate-native-design.py'),'--check'],capture_output=True,text=True)
if check.returncode:errors.append({'rule':'generated assets drift','detail':check.stdout+check.stderr})
result={'canonicalAssets':len(assets),'semanticNames':len(reg['icons']),'staticSemanticCallsites':len(uses),
 'staticallyUsedAssets':len({x['asset'] for x in uses}),'unreferencedCanonicalAssets':sorted(set(assets)-{x['asset'] for x in uses}),
 'note':'Dynamic registry lookups and compatibility wrappers may use additional assets; unreferenced does not authorize deletion.',
 'inlineExceptions':inline,'errors':errors,'uses':uses,'generator':check.stdout.strip()}
if args.output:Path(args.output).write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({k:v for k,v in result.items() if k not in ['uses','inlineExceptions','unreferencedCanonicalAssets']},ensure_ascii=False,indent=2))
raise SystemExit(bool(errors))
