#!/usr/bin/env python3
"""Generate native palettes and vectors from the same supplied design source as Web."""
import argparse, json, re, xml.etree.ElementTree as ET
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
tokens=json.loads((ROOT/'web/src/ui-kit/tokens.json').read_text())
android=ROOT/'android/app/src/main/java/com/touliao/app/ui'
ios=ROOT/'ios/Touliao'
outputs={}
def write(path,text):outputs[path]=text

def rgba(value):
    if value.startswith('#'): return 'FF'+value[1:].upper()
    parts=re.findall(r'[\d.]+',value)
    return f'{round(float(parts[3])*255):02X}'+''.join(f'{int(v):02X}' for v in parts[:3])
colors=tokens['color']
fields=list(colors['light'])+['readableMuted','readableDanger']
# Match the contrast correction already used by Web, while preserving source tokens.
for mode in colors:
    for dest,key,pct in [('readableMuted','textMuted',.92),('readableDanger','danger',.85)]:
        a=colors[mode][key];b=colors[mode]['text']
        colors[mode][dest]=a if mode=='dark' else '#'+''.join(f'{round(int(a[i:i+2],16)*pct+int(b[i:i+2],16)*(1-pct)):02x}' for i in (1,3,5))
kt='''// Generated by scripts/generate-native-design.py; do not edit.
package com.touliao.app.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.runtime.staticCompositionLocalOf

data class TouliaoPalette(
'''+''.join(f'    val {key}: Color,\n' for key in fields)+')\n\n'
for mode in colors:
    kt+=f'val Touliao{mode.title()}Palette = TouliaoPalette(\n'+''.join(f'    {key} = Color(0x{rgba(colors[mode][key])}),\n' for key in fields)+')\n\n'
kt+='val LocalTouliaoPalette = staticCompositionLocalOf { TouliaoLightPalette }\n'
write(android/'theme/DesignTokens.kt',kt)
sw='''// Generated by scripts/generate-native-design.py; do not edit.
import SwiftUI
import UIKit

enum TouliaoDesign {
    private static func adaptive(_ light: UInt32, _ dark: UInt32) -> Color {
        Color(UIColor { traits in
            let value = traits.userInterfaceStyle == .dark ? dark : light
            return UIColor(red: CGFloat((value >> 16) & 255) / 255,
                           green: CGFloat((value >> 8) & 255) / 255,
                           blue: CGFloat(value & 255) / 255,
                           alpha: CGFloat((value >> 24) & 255) / 255)
        })
    }
'''
sw+=''.join(f'    static let {key} = adaptive(0x{rgba(colors["light"][key])}, 0x{rgba(colors["dark"][key])})\n' for key in fields)+'}\n'
write(ios/'UI/Theme/DesignTokens.swift',sw)

def path_data(el):
    tag=el.tag.rsplit('}',1)[-1];a=el.attrib
    if tag=='path':return a['d']
    if tag=='line':return f'M{a["x1"]} {a["y1"]} L{a["x2"]} {a["y2"]}'
    if tag=='polygon':return 'M'+a['points']+' Z'
    if tag=='circle':
        x,y,r=(float(a[k]) for k in ('cx','cy','r'))
        return f'M{x-r:g} {y:g} A{r:g} {r:g} 0 1 0 {x+r:g} {y:g} A{r:g} {r:g} 0 1 0 {x-r:g} {y:g}'
    if tag=='rect':
        x,y,w,h=(float(a.get(k,0)) for k in ('x','y','width','height'))
        rx=min(float(a.get('rx',0)),w/2);ry=min(float(a.get('ry',rx)),h/2)
        return f'M{x+rx:g} {y:g} H{x+w-rx:g} A{rx:g} {ry:g} 0 0 1 {x+w:g} {y+ry:g} V{y+h-ry:g} A{rx:g} {ry:g} 0 0 1 {x+w-rx:g} {y+h:g} H{x+rx:g} A{rx:g} {ry:g} 0 0 1 {x:g} {y+h-ry:g} V{y+ry:g} A{rx:g} {ry:g} 0 0 1 {x+rx:g} {y:g} Z'
    raise ValueError(tag)
registry=json.loads((ROOT/'web/src/ui-kit/icon-registry.json').read_text())
icons=sorted((ROOT/'web/src/ui-kit/icons').glob('*.svg'))
assert len(icons)>=136
stroke=registry['strokeWidth']
kt='''// Generated by scripts/generate-native-design.py. Private geometry, use TouliaoIcons in views.
package com.touliao.app.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

internal object DesignIcons {
    private fun vector(name: String, vararg paths: Pair<String, Boolean>): ImageVector = ImageVector.Builder(
        name, 24.dp, 24.dp, 24f, 24f
    ).apply {
        paths.forEach { (data, filled) -> addPath(
            pathData = PathParser().parsePathString(data).toNodes(),
            fill = if (filled) SolidColor(Color.Black) else null,
            stroke = SolidColor(Color.Black), strokeLineWidth = STROKE,
            strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round,
        ) }
    }.build()
'''.replace('STROKE',f'{stroke}f')
webpaths={}
for p in icons:
    root=ET.fromstring(p.read_text())
    assert root.get('viewBox')=='0 0 24 24',p
    assert float(root.get('stroke-width'))==stroke,p
    assert root.get('stroke-linecap')==registry['linecap'] and root.get('stroke-linejoin')==registry['linejoin'],p
    name=''.join(w.title() for w in p.stem.split('-'))
    paths=[(path_data(el),el.get('fill','none')!='none') for el in root]
    kt+=f'    val {name}: ImageVector by lazy {{ vector("{p.stem}", '+', '.join(json.dumps(d)+' to '+str(fill).lower() for d,fill in paths)+') }\n'
    webpaths[p.stem]=[[el.tag.rsplit('}',1)[-1],dict(el.attrib)] for el in root]
    asset=ios/f'Assets.xcassets/DesignIcons/tl-{p.stem}.imageset'
    write(asset/(p.stem+'.svg'),p.read_text().replace('currentColor','#000000'))
    write(asset/'Contents.json',json.dumps({'images':[{'filename':p.stem+'.svg','idiom':'universal'}],'info':{'author':'xcode','version':1},'properties':{'preserves-vector-representation':True,'template-rendering-intent':'template'}},indent=2)+'\n')
kt+='}\n';write(android/'DesignIcons.kt',kt)
write(ROOT/'web/src/ui-kit/icon-paths.json',json.dumps(webpaths,separators=(',',':'))+'\n')
write(ios/'Assets.xcassets/DesignIcons/Contents.json',json.dumps({'info':{'author':'xcode','version':1}},indent=2)+'\n')
for name,asset in registry['icons'].items():assert asset in webpaths,(name,asset)
kt='''// Generated from web/src/ui-kit/icon-registry.json. Business views use semantic names only.
package com.touliao.app.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import com.touliao.app.ui.theme.LocalTouliaoPalette

object TouliaoIcons {
'''
for name,asset in registry['icons'].items():
    kt+=f'    val {name[0].upper()+name[1:]} get() = DesignIcons.{"".join(w.title() for w in asset.split("-"))}\n'
kt+='}\n\nobject IconSize {\n'+''.join(f'    val {n.title()} = {v}.dp\n' for n,v in registry['sizes'].items())+'}\n\nobject IconTouchTarget {\n'+''.join(f'    val {n[0].upper()+n[1:]} = {v}.dp\n' for n,v in registry['touchTargets'].items())+'}\n\nobject IconColor {\n'
for n,key in registry['colors'].items():
    kt+=f'    val {n[0].upper()+n[1:]}: Color\n        @Composable @ReadOnlyComposable get() = LocalTouliaoPalette.current.{key}\n'
kt+='}\n';write(android/'TouliaoIcons.kt',kt)
sw='''// Generated from web/src/ui-kit/icon-registry.json. No SF Symbol fallback.
import SwiftUI

enum TouliaoIconRegistry {
    static let assets: [String: String] = [
'''+''.join(f'        "{n}": "{a}",\n' for n,a in registry['icons'].items())+'    ]\n}\n\nenum IconSize: CGFloat, CaseIterable {\n'+''.join(f'    case {n} = {v}\n' for n,v in registry['sizes'].items())+'}\n\nenum IconTouchTarget {\n'+''.join(f'    static let {n}: CGFloat = {v}\n' for n,v in registry['touchTargets'].items())+'}\n\nenum IconColor {\n'+''.join(f'    static let {n} = TouliaoDesign.{key}\n' for n,key in registry['colors'].items())+'}\n'
write(ios/'UI/Components/TouliaoIconRegistry.swift',sw)
css='/* Generated from icon-registry.json; geometry/size/tint have one owner. */\n:root {\n'
css+=''.join(f'  --icon-{n}: {v}px;\n' for n,v in registry['sizes'].items())+'}\n'
css+='html.touliao-ui body {\n'
for n,key in registry['colors'].items():
    cssname=re.sub(r'([A-Z])',lambda m:'-'+m[1].lower(),n)
    if key=='iconOnDark':value='#ffffff'
    elif key=='iconOnLight':value='#17212e'
    else:value='var(--tl-'+re.sub(r'([A-Z])',lambda m:'-'+m[1].lower(),key)+')'
    css+=f'  --icon-{cssname}: {value};\n'
css+='}\n'
css+='''html.touliao-ui body svg.tl-icon { fill: none !important; flex-shrink: 0; vertical-align: middle; }
html.touliao-ui body .tl-icon-button { display: inline-flex; align-items: center; justify-content: center; min-width: 36px; min-height: 36px; }
html.touliao-ui body .tl-icon-button:disabled { color: var(--icon-disabled); }
html.touliao-ui body .wc-ctx-item { display: flex; align-items: center; gap: 8px; }
html.touliao-ui body .wc-ctx-item.danger { color: var(--icon-danger); }
html.touliao-ui body .tl-icon-label { display: inline-flex; align-items: center; gap: 8px; }
html.touliao-ui body .tl-icon-placeholder { display: inline-flex; align-items: center; justify-content: center; color: var(--icon-secondary); }
html.touliao-ui body :is(.wc-tool-btn, .wc-send-btn, .wc-more-icon, .wc-chat-header-btn, .m-tab-ico, .wc-sidebar-btn, .cm-circle-btn-icon, .gcm-control) { --tl-icon-size: var(--icon-md); }
html.touliao-ui body .wc-state-icon { --tl-icon-size: var(--icon-xl); }
html.touliao-ui body .wc-more-icon { color: var(--icon-on-dark); }
html.touliao-ui body .cm-circle-btn-icon { color: var(--icon-on-dark); }
html.touliao-ui body :is(.wc-voice-play-icon, .wc-voice-play-icon-offset) { color: inherit; }

html.touliao-ui body .m-tab-ico svg.tl-icon { width: var(--icon-md); height: var(--icon-md); }
html.touliao-ui body :is(.gi-fill-red, .gi-stroke-red) { color: var(--icon-danger); }
html.touliao-ui body .cm-circle-btn-icon { display: flex; align-items: center; justify-content: center; }
@media (max-width: 767px) {
  html.touliao-ui body :is(.tl-icon-button, .wc-send-btn) { min-width: 44px; min-height: 44px; }
}
'''
write(ROOT/'web/src/ui-kit/icons.css',css)
for p,s in outputs.items():
    if args.check:
        if not p.is_file() or p.read_text()!=s:raise SystemExit('Generated design file differs: '+str(p.relative_to(ROOT)))
    else:p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s)
print(f'{"Checked" if args.check else "Generated"} palettes, registry and {len(icons)} icons for each platform ({len(outputs)} files).')
