#!/usr/bin/env python3
"""Generate native palettes and vectors from the same supplied design source as Web."""
import argparse, json, re, xml.etree.ElementTree as ET
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
tokens=json.loads((ROOT/'web/src/ui-kit/tokens.json').read_text())
android=ROOT/'android/app/src/main/java/com/touliao/app/ui'
ios=ROOT/'ios/Touliao'
outputs={}
def write(path,text):outputs[path]=text

def rgba(value):
    if value.startswith('#'): return 'FF'+value[1:].upper()
    parts=re.findall(r'[\d.]+',value)
    return f'{round(float(parts[3])*255):02X}'+''.join(f'{int(v):02X}' for v in parts[:3])
colors=tokens['color']
fields=list(colors['light'])+['readableMuted','readableDanger']
# Match the contrast correction already used by Web, while preserving source tokens.
for mode in colors:
    for dest,key,pct in [('readableMuted','textMuted',.92),('readableDanger','danger',.85)]:
        a=colors[mode][key];b=colors[mode]['text']
        colors[mode][dest]=a if mode=='dark' else '#'+''.join(f'{round(int(a[i:i+2],16)*pct+int(b[i:i+2],16)*(1-pct)):02x}' for i in (1,3,5))
kt='''// Generated by scripts/generate-native-design.py; do not edit.
package com.touliao.app.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.runtime.staticCompositionLocalOf

data class TouliaoPalette(
'''+''.join(f'    val {key}: Color,\n' for key in fields)+')\n\n'
for mode in colors:
    kt+=f'val Touliao{mode.title()}Palette = TouliaoPalette(\n'+''.join(f'    {key} = Color(0x{rgba(colors[mode][key])}),\n' for key in fields)+')\n\n'
kt+='val LocalTouliaoPalette = staticCompositionLocalOf { TouliaoLightPalette }\n'
write(android/'theme/DesignTokens.kt',kt)
sw='''// Generated by scripts/generate-native-design.py; do not edit.
import SwiftUI
import UIKit

enum TouliaoDesign {
    private static func adaptive(_ light: UInt32, _ dark: UInt32) -> Color {
        Color(UIColor { traits in
            let value = traits.userInterfaceStyle == .dark ? dark : light
            return UIColor(red: CGFloat((value >> 16) & 255) / 255,
                           green: CGFloat((value >> 8) & 255) / 255,
                           blue: CGFloat(value & 255) / 255,
                           alpha: CGFloat((value >> 24) & 255) / 255)
        })
    }
'''
sw+=''.join(f'    static let {key} = adaptive(0x{rgba(colors["light"][key])}, 0x{rgba(colors["dark"][key])})\n' for key in fields)+'}\n'
write(ios/'UI/Theme/DesignTokens.swift',sw)

def path_data(el):
    tag=el.tag.rsplit('}',1)[-1];a=el.attrib
    if tag=='path':return a['d']
    if tag=='line':return f'M{a["x1"]} {a["y1"]} L{a["x2"]} {a["y2"]}'
    if tag=='polygon':return 'M'+a['points']+' Z'
    if tag=='circle':
        x,y,r=(float(a[k]) for k in ('cx','cy','r'))
        return f'M{x-r:g} {y:g} A{r:g} {r:g} 0 1 0 {x+r:g} {y:g} A{r:g} {r:g} 0 1 0 {x-r:g} {y:g}'
    if tag=='rect':
        x,y,w,h=(float(a.get(k,0)) for k in ('x','y','width','height'))
        rx=min(float(a.get('rx',0)),w/2);ry=min(float(a.get('ry',rx)),h/2)
        return f'M{x+rx:g} {y:g} H{x+w-rx:g} A{rx:g} {ry:g} 0 0 1 {x+w:g} {y+ry:g} V{y+h-ry:g} A{rx:g} {ry:g} 0 0 1 {x+w-rx:g} {y+h:g} H{x+rx:g} A{rx:g} {ry:g} 0 0 1 {x:g} {y+h-ry:g} V{y+ry:g} A{rx:g} {ry:g} 0 0 1 {x+rx:g} {y:g} Z'
    raise ValueError(tag)
icons=sorted((ROOT/'web/src/ui-kit/icons').glob('*.svg'));assert len(icons)==136
kt='''// Generated from the supplied SVG geometry; currentColor is supplied by Icon tint.
package com.touliao.app.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

object DesignIcons {
    private fun vector(name: String, vararg paths: String): ImageVector = ImageVector.Builder(
        name, 24.dp, 24.dp, 24f, 24f
    ).apply {
        paths.forEach { data -> addPath(
            pathData = PathParser().parsePathString(data).toNodes(),
            fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = 1.8f,
            strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round,
        ) }
    }.build()
'''
for p in icons:
    name=''.join(w.title() for w in p.stem.split('-'))
    paths=[path_data(el) for el in ET.fromstring(p.read_text())]
    kt+=f'    val {name}: ImageVector by lazy {{ vector("{p.stem}", '+', '.join(json.dumps(d) for d in paths)+') }\n'
    asset=ios/f'Assets.xcassets/DesignIcons/tl-{p.stem}.imageset'
    write(asset/(p.stem+'.svg'),p.read_text().replace('currentColor','#000000'))
    write(asset/'Contents.json',json.dumps({'images':[{'filename':p.stem+'.svg','idiom':'universal'}],'info':{'author':'xcode','version':1},'properties':{'preserves-vector-representation':True,'template-rendering-intent':'template'}},indent=2)+'\n')
kt+='}\n';write(android/'DesignIcons.kt',kt)
write(ios/'Assets.xcassets/DesignIcons/Contents.json',json.dumps({'info':{'author':'xcode','version':1}},indent=2)+'\n')
for p,s in outputs.items():
    if args.check:
        if not p.is_file() or p.read_text()!=s:raise SystemExit('Generated native design file differs: '+str(p.relative_to(ROOT)))
    else:p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s)
print(f'{"Checked" if args.check else "Generated"} native palettes and {len(icons)} icons for each platform ({len(outputs)} files).')
