// Generated from web/src/ui-kit/icon-registry.json. No SF Symbol fallback.
import SwiftUI

enum TouliaoIconRegistry {
    static let assets: [String: String] = [
        "acceptCall": "phone",
        "add": "plus",
        "addFriend": "user-round-plus",
        "addMember": "user-round-plus",
        "adjustments": "sliders-horizontal",
        "allTypes": "layers",
        "announcement": "megaphone",
        "appearance": "palette",
        "archive": "folder",
        "arrowDownToLine": "arrow-down-to-line",
        "arrowLeft": "arrow-left",
        "back": "chevron-left",
        "backpack": "backpack",
        "badgeCheck": "badge-check",
        "batteryFull": "battery-full",
        "bellRing": "bell-ring",
        "blocked": "shield-ban",
        "bluetooth": "bluetooth",
        "bluetoothOff": "bluetooth-off",
        "brushCleaning": "brush-cleaning",
        "calendar": "calendar-days",
        "callIncoming": "phone-incoming",
        "callMissed": "phone-missed",
        "callOutgoing": "phone-outgoing",
        "camera": "camera",
        "cameraOff": "video-off",
        "cameraSwitch": "switch-camera",
        "chat": "message-circle",
        "check": "check",
        "clear": "x",
        "clearCache": "trash-2",
        "clock3": "clock-3",
        "close": "x",
        "collapse": "chevron-up",
        "comment": "message-circle",
        "component": "component",
        "computer": "monitor",
        "contact": "user-round",
        "contacts": "contact-round",
        "copy": "copy",
        "darkMode": "moon",
        "decorativeContact": "contact",
        "decorativeDelete": "delete",
        "decorativeFile": "file",
        "decorativeGroup": "group",
        "delete": "trash-2",
        "device": "monitor-smartphone",
        "disclosure": "chevron-right",
        "discover": "compass",
        "download": "download",
        "earpiece": "phone",
        "edit": "pencil",
        "emoji": "smile",
        "empty": "circle-help",
        "ephemeral": "clock",
        "error": "circle-alert",
        "expand": "chevron-down",
        "externalLink": "external-link",
        "favorite": "bookmark",
        "file": "paperclip",
        "fileContent": "file-text",
        "files": "files",
        "filter": "filter",
        "focus": "focus",
        "folder": "folder",
        "folderOpen": "folder-open",
        "forward": "forward",
        "fullscreen": "expand",
        "ghost": "ghost",
        "group": "users",
        "groupInfo": "users",
        "hangup": "phone-off",
        "help": "circle-help",
        "hidePassword": "eye-off",
        "image": "image",
        "images": "images",
        "info": "info",
        "keyboard": "keyboard",
        "laptop": "laptop",
        "leaf": "leaf",
        "lightMode": "sun",
        "like": "heart",
        "link": "link",
        "location": "map-pin",
        "lock": "lock-keyhole",
        "logout": "log-out",
        "mention": "at-sign",
        "mergedMessages": "messages-square",
        "message": "message-square",
        "microphone": "mic",
        "microphoneMuted": "mic-off",
        "minimize": "minus",
        "more": "ellipsis",
        "mountainSnow": "mountain-snow",
        "multiselect": "circle-check",
        "mute": "bell-off",
        "navigation": "navigation",
        "network": "wifi",
        "networkOffline": "wifi-off",
        "next": "arrow-right",
        "notification": "bell",
        "nudge": "hand",
        "owner": "crown",
        "panelTop": "panel-top",
        "panelsTopLeft": "panels-top-left",
        "passwordReset": "key-round",
        "pause": "pause",
        "phone": "phone",
        "phoneCall": "phone-call",
        "phoneNumber": "smartphone",
        "pin": "pin",
        "play": "play",
        "profile": "user-round",
        "qrcode": "qr-code",
        "quote": "quote",
        "radio": "radio",
        "recall": "undo-2",
        "redPacket": "mail",
        "refresh": "refresh-cw",
        "rejectCall": "phone-off",
        "removeMember": "user-round-x",
        "reply": "reply",
        "rose": "rose",
        "rotateCw": "rotate-cw",
        "scan": "scan-line",
        "schedule": "clock",
        "screenShare": "screen-share",
        "screenshot": "scissors",
        "scrollDown": "arrow-down",
        "search": "search",
        "searchEmpty": "search-x",
        "security": "shield-check",
        "selectAll": "check-check",
        "selected": "circle-check",
        "send": "send",
        "server": "hard-drive",
        "settings": "settings",
        "settings2": "settings-2",
        "share": "share-2",
        "shield": "shield",
        "shieldAlert": "shield-alert",
        "showPassword": "eye",
        "signal": "signal",
        "sparkles": "sparkles",
        "speaker": "volume-2",
        "speakerOff": "volume-2-off",
        "squarePen": "square-pen",
        "star": "star",
        "stickers": "smile-plus",
        "stop": "stop",
        "tag": "tag",
        "tags": "tags",
        "text": "text",
        "ticket": "tag",
        "transfer": "transfer",
        "unselected": "circle",
        "up": "chevrons-up",
        "upload": "upload",
        "user": "user",
        "userPlus": "user-plus",
        "video": "video",
        "videoCall": "video",
        "view": "view",
        "voice": "mic",
        "voiceCall": "phone",
        "wallet": "wallet",
        "warning": "triangle-alert",
    ]
}

enum IconSize: CGFloat, CaseIterable {
    case xs = 16
    case sm = 20
    case md = 24
    case lg = 32
    case xl = 40
}

enum IconTouchTarget {
    static let ios: CGFloat = 44
    static let android: CGFloat = 48
    static let webMobile: CGFloat = 44
    static let desktop: CGFloat = 36
}

enum IconColor {
    static let primary = TouliaoDesign.text
    static let secondary = TouliaoDesign.readableMuted
    static let tertiary = TouliaoDesign.readableMuted
    static let selected = TouliaoDesign.primary
    static let disabled = TouliaoDesign.textDisabled
    static let danger = TouliaoDesign.readableDanger
    static let onDark = TouliaoDesign.iconOnDark
    static let onLight = TouliaoDesign.iconOnLight
    static let onAccent = TouliaoDesign.primaryForeground
}
